!obj:pylearn2.train.Train {
    dataset: &train !obj:digits_dataset.DigitsDataset {
        path: '/path/to/train.csv',
        one_hot: 1
    },
    model: !obj:pylearn2.monitor.push_monitor {
        model: !pkl: "digits_best.pkl",
        name: "monitor_stage_0"
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 100,
        learning_rate: 0.0615082606673,
        init_momentum: 0.694376766682,

        monitoring_dataset:
        {
                'train' : *train,
                'valid' : !obj:digits_dataset.DigitsDataset {
                    path: '/path/to/test_v.csv',
                    one_hot: 1,
                    expect_headers: 0,
                    expect_labels: 1
                }
        }, 

        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: { 'h0' : .8 },
            input_scales: { 'h0': 1. }
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MatchChannel {
            channel_name: "valid_objective",
            prev_channel_name: "train_objective",
            prev_monitor_name: "monitor_stage_0"
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.000004,
            min_lr: .000001
        }
    },
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}

